language: python
python:
  - "3.6"
env:
  - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
  - MY_ENV
install:
  - pip install pytest pytest-cov
  - pip install .
# command to run tests
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
script:
  - pytest --cov=mlutils
  - echo $MY_ENV
  - echo "Testing output"
after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -r $CC_TEST_REPORTER_ID