sudo: required
language: python
python:
  - "3.6"
services:
  - mysql
  - docker
before_install:
  - sudo apt-get -qq update
  - docker pull minio/minio
  - docker run -d -p 9000:9000 -e "MINIO_ACCESS_KEY=$S3_ACCESS_KEY" -e "MINIO_SECRET_KEY=$S3_SECRET_KEY" minio/minio server /data
  - sleep 120
  - docker pull minio/mc
  - docker run --network="host" --entrypoint=/bin/sh minio/mc -c "mc config host add dj-s3 http://$S3_ENDPOINT $S3_ACCESS_KEY $S3_SECRET_KEY;mc mb $S3_BUCKET;mc policy download $S3_BUCKET;exit 0;"
  - sudo apt-get install -y libblas-dev liblapack-dev libatlas-dev gfortran
  - sudo apt-get install -y graphviz graphviz-dev pkg-config
  - mysql -e "create user 'datajoint'@'%' identified by 'datajoint'; GRANT ALL PRIVILEGES ON \`djtest\_%\`.* TO 'datajoint'@'%';" -uroot
  - mysql -e "create user 'djview'@'%' identified by 'djview'; GRANT SELECT ON \`djtest\_%\`.* TO 'djview'@'%';" -uroot
install:
  - pip install nose nose-cov python-coveralls
# command to run tests
script:
  - pytest